###
POST https://localhost:7656/users/Signup HTTP/1.1
content-type : application/json"

{
    "firstName" : "Anu", "lastName" : "Siraj", "email" : "angu.srajencir@gmail.com", "password" : "Gr@y&At0m"
}

###
POST https://localhost:7656/users/signin HTTP/1.1
content-type : application/json"

{
    "email" : "shu@gmail.com", "password" : "Gr@y&At0m"
}

###
POST https://localhost:7656/roles/add HTTP/1.1
content-type : application/json"

{
    "roleName" : "DEV"
}
###
# POST https://localhost:7656/users/Signin HTTP/1.1
# content-type : application/json"

# {
#     "firstName" : "Anu", "lastName" : "Siraj", "email" : "anu.sraj@gmail.com", "password" : "Gr@y&At0m"
# }


# ###
POST https://localhost:7656/images HTTP/1.1
content-type : application/json"

{
    "Url" : [ "https://u=image.png" ]
}
###
POST https://localhost:7656/carts HTTP/1.1
content-type : application/json"

{
  "cartName": "Cart2",
  "cartStatus": "not available"
}


# ###
# GET https://localhost:7656/images/4

# ###
# PUT https://localhost:7656/images/2 HTTP/1.1
# content-type : application/json"

# {
#     "Url" : [ "https://u=image1.png" ,"https://u=image2.png", "https://u=image.png" ]
# }

# ###
# DELETE https://localhost:7656/images/4

# PUT https://localhost:7656/products/2 HTTP/1.1
# content-type : application/json"

# {
#     "name": "Sandals", "price" : 6, "description" : "Nike Shoe - New Arrival" ,"categoryId" :2
# }



# POST https://localhost:7656/categories HTTP/1.1
# content-type : application/json"

# {
#     "name": "Electronics"
# }

# PUT https://localhost:7656/categories/1 HTTP/1.1
# content-type : application/json"

# {
#     "name": "Bag"
# }

# DELETE https://localhost:7656/categories/2
# GET https://localhost:7656/categories?page=6&itemsperpage=2

# 
