###
POST https://localhost:7656/products HTTP/1.1
content-type : application/json"

{
    "name": "Charger", "price" : 9.123, "category": "Shoes","description" : "Crucj", "categoryId" : 10,
    "images" : {"url" : ["https://image.png","https://image.png","https://image.png"]}
    
}

###
GET https://localhost:7656/carts HTTP/1.1
content-type : application/json"

{
    
}


###
GET https://localhost:7656/carts

###
GET https://localhost:7656/products

###
GET https://localhost:7656/products


###
DELETE https://localhost:7656/products/3

###
PUT https://localhost:7656/products/36 HTTP/1.1
content-type : application/json"

{
    "name": "Sandals","description" : "Crucj", "categoryId" : 10, "price" : 10,
    "images" : {"url" : ["https://image.png","https://image.png","https://image.png"] }
}



### 
POST https://localhost:7656/categories HTTP/1.1
content-type : application/json"

{
    "name": "FURNITURE", "images" : {"url" : ["https://image.png"]} 
}

###
PUT https://localhost:7656/categories/10 HTTP/1.1
content-type : application/json"

{
    "name": "Electronics", "images" : {"url" : ["https://image.png"]}
}

###
GET https://localhost:7656/categories/5
###
GET https://localhost:7656/categories/page1&itemsperpage=3


