###
POST https://localhost:7656/products HTTP/1.1
content-type : application/json"

{
    "name": "Charger", "price" : 9.123, "description" : "Crucj", "category": "Shoes", "categoryId" : 8,
    "images" : {"url" : ["https://image.png","https://image.png","https://image.png"] } 
}
###
GET https://localhost:7656/products?page=1&itemsperpage=3

###
GET https://localhost:7656/products/filter?name=charger&price_min=1&price_max=10&categoryId=1

###
GET https://localhost:7656/products/2


###
DELETE https://localhost:7656/products/3

###
PUT https://localhost:7656/products/34 HTTP/1.1
content-type : application/json"

{
    "name": "Sandals","description" : "Crucj", "images" : {"url" : ["https://image.png","https://image.png","https://image.png"] }
}



### 
POST https://localhost:7656/categories HTTP/1.1
content-type : application/json"

{
    "name": "FURNITURE", "images" : {"url" : ["https://image.png"]} 
}

###
PUT https://localhost:7656/categories/1 HTTP/1.1
content-type : application/json"

{
    "name": "Bag"
}

###
GET https://localhost:7656/categories/5
###
GET https://localhost:7656/categories?page=1&itemsperpage=10

