POST https://localhost:5001/products HTTP/1.1
content-type : application/json" 

{
    "name": "Shoe", "price" : "100", "description" : "Nike Shoe - New Arrival"
}

# GET https://localhost:5001/products