# POST https://localhost:7656/products HTTP/1.1
# content-type : application/json"

# {
#     "name": "Anu", "price" : 9.123, "description" : "Crucj", "category": "Shoes", "categoryId" : 2
# }

# GET https://localhost:7656/products/?page=3&itemsperpage=1




# DELETE https://localhost:7656/products/2

# PUT https://localhost:7656/products/2 HTTP/1.1
# content-type : application/json"

# {
#     "name": "Sandals", "price" : 6, "description" : "Nike Shoe - New Arrival" ,"categoryId" :2
# }



# POST https://localhost:7656/categories HTTP/1.1
# content-type : application/json"

# {
#     "name": "Bag"
# }

# PUT https://localhost:7656/categories/1 HTTP/1.1
# content-type : application/json"

# {
#     "name": "Bag"
# }

# GET https://localhost:7656/categories
# GET https://localhost:7656/categories/2

# 
